Dan 35
Da-Niim/Da-Niim-Server pull request #19
Opened 2024-01-24 10:24 UTC by mingi3442

### TODO
- 팔로우 기능 추가
- 언팔로우 기능 추가
- user Repository Refactoring 
- 사용하지 않는 선언문 제거

2024-01-25 09:47 UTC, jinsy731 requested changes

2024-01-25 09:47 UTC, jinsy731 commented on src/follow/follow.service.ts
중요한건 아니지만 addFollower/Following, removeFollower/Following 대신 follow(), unfollow()로 하고 도메인 로직을 안으로 넣는 것도 좋을듯

currentUser.follow(targetUser)

follow 메서드 안에서 currentUser와 targetUser의 follower, following 추가 처리

이런식으로?

2024-01-25 10:35 UTC, mingi3442 commented on src/follow/follow.service.ts
수정 해서 다시 커밋했습니다 😀

2024-01-30 20:26 UTC, jinsy731 approved these changes

2024-01-30 20:26 UTC, jinsy731 commented on src/follow/follow.service.ts
currentUser : User 타입
follow() -> User 안에 있는 메소드

follow() 메서드 안에서 follower / following 추가

2024-01-30 20:26 UTC, merged